### PR TITLE
Tibia Client ver. 10.100 support

### PR DESCRIPTION
**Pull request by thexamx**
I added suport to newest Tibia version called "10" or "10.100".

Items.otb is the one from forgottenserver, but updated to version 10.100.

### CODE REVIEW

**Comment by Elime1** [comment]
Where do I get the tibia 10.100 client? =P

**Comment by thexamx** [comment]
http://tibia-clients.com

**Comment by Elime1** [comment]
Ok, I selected 11.x and then 10.00 client from the site. 

When I open the editor without any client configured it still asks for 10.98 installation folder. Then I went to Map -> Properties and selected 10.100 and it asked me to navigate to 10.100 installation folder. But when I select the folder it says it could not locate the .dat and .spr files. Not sure, but it seems like signatures are wrong.

**Comment by thexamx** [comment]
For some reason this client from this site got changed spr signature and it's other from the one I'm using.
But if we are going to use this one, then I will push commit with changed signature.

**Comment by Elime1** [comment]
That's strage. Where did you get your original client from?

**Comment by diath** [comment]
>For some reason client from this site got changed spr signature and it's other from the one I'm using.
>But if we are going to use this one, then I will push commit with changed signature.

This is because the latest version of the legacy client stays at version 10.100 but they keep updating the .dat and .spr files to match the Tibia 11 client in regards to items and such.

**Comment by thexamx** [comment]
You are right!
I got it now :D

**Comment by Elime1** [comment]
So they will probably change it soon again...?

**Comment by Elime1** [comment]
But we can just make a new issue when that happens

**Pull request merged**
