### PR TITLE
Paste position into teleporter

### PR DESCRIPTION
**Pull request by leleco95**
Any copy position format is valid for pasting position into teleporters. #241

### CODE REVIEW

**Comment by diath** [comment]
You could make the templates a static array instead of compiling the regexp every time a position is pasted.

**Comment by Sickness-chan** [comment]
With https://github.com/hjnilsson/rme/pull/268 you can paste positions into the properties window, as it is intended

**Comment by leleco95** [comment]
Any reason it hasn't been merged?

**Comment by Sickness-chan** [comment]
Because they took too long and I just closed the PR instead

**Comment by leleco95** [comment]
Well, since there's already another solution I'll just close it too.

**Pull request closed without merging**
