### PR TITLE
Fix OSX LibArchive include path

### PR DESCRIPTION
**Pull request by gpedro**

### CODE REVIEW

**Comment by hjnilsson** [comment]
Lots of good changes here, why did you close it?

**Comment by gpedro** [comment]
@Mignari and some guys are updating RME. Look https://github.com/ottools/rme/
My patch-fix is to they.

**Comment by Mignari** [comment]
This PR has custom contents like #19 , but now the features are enabled by an external file. If you want, can merge all changes or any fixes/features. :+1:

**Comment by hjnilsson** [comment]
I've merged it in. Great work! If you prefer, I can add you as developers on this project instead. So you can commit directly instead. :)

**Comment by Mignari** [comment]
Yes, It would be great :D

**Comment by hjnilsson** [comment]
I have added you as a collaborated, as well as gpedro. You can commit directly to the RME repository now instead. :)

Anyone else I should add?

**Pull request merged**
