### PR TITLE
[Bug] Fixes crash when saving the map with spawn place set to position without tile

### PR DESCRIPTION
**Pull request by Costallat**
- Adds check when saving the map to not crash when the map has some
spawn position set to a place where there isn't any tile.

Attached map to test.

[crash.map.tar.gz](https://github.com/hjnilsson/rme/files/2275891/crash.map.tar.gz)

Signed-off-by: Renato Foot <costallat@hotmail.com>

### CODE REVIEW

**Comment by Elime1** [comment]
Not able to reproduce. But I'm under macOS, so it might be different. Will try on windows later.

**Comment by Mignari** [comment]
I can reproduce it.

1. Add missing files to attached map.

crash-spawn.xml
```XML
<?xml version="1.0"?>
<spawns>
	<spawn centerx="1008" centery="1028" centerz="7" radius="5" />
</spawns>
```
crash-house.xml
```XML
<?xml version="1.0"?>
<houses />
```
2. Menu Edit > Other Options > Remove all unreachable tiles...
3. Save the map.

The Costallat's changes fixed it, but maybe occur because of a problem elsewhere in the code.
I've never used Remove all unreachable tiles before

**Comment by Elime1** [comment]
It would probably be annoying if the spawn was removed as soon as you remove the ground. Just because you did some temporary edit. So in this case I think it is better to handle it on save.
But maybe check it like this:
`if (tile != nullptr && tile->spawn != nullptr && tile->hasGround())`
And remove the assertions

**Comment by Elime1** [comment]
With your lates change you are skipping every valid tile. That's the opposite of what we want.

**Pull request closed without merging**
