### PR TITLE
[Bug] Fixes crash when selecting chest item but close the window instead of selecting some item

### PR DESCRIPTION
**Pull request by Costallat**
Open the chest, try to select one item, but instead of selecting one, close de window and close the chest window.

[test_map.tar.gz](https://github.com/hjnilsson/rme/files/2280609/test_map.tar.gz)

Signed-off-by: Renato Foot Guimarães Costallat <renato.costallat@gmail.com>

### CODE REVIEW

**Comment by Mignari** [comment]
I can't reproduce it. Can you explain the steps?

**Comment by Costallat** [comment]
1 - Open the attached map
2 - Open the chest
3 - Click in the first slot to choose one item
4 - Close the windows using on the 'X' button
5 - Close the chest with the "ok" button
6 - Double click the chest
7 - Crash

I can reproduce it here, check with those steps.

Tks

**Comment by Elime1** [comment]
I can reproduce it. It is probably better to make sure no null object gets added when closing the window.

**Comment by Elime1** [comment]
Did this fix: db48aa6e36e5723dbc93f831852fe352719fdf5a Could you try it out?

**Comment by Mignari** [comment]
the db48aa6e36e5723dbc93f831852fe352719fdf5a fixed it.

**Pull request closed without merging**
