### PR TITLE
Added actionid/uniqueid to item search

### PR DESCRIPTION
**Pull request by BenDol**
Also fixed some issues with the item list refresh.

### CODE REVIEW

**Comment by Mignari** [comment]
The 'NumberTextCtrl' component is more apropriate for this case. You can use the 'GetIntValue' method.
I got crashes sometimes:
1-Open a big map.
2-Open the Find Items window and insert an invalid value, press Ok button.
3-Go to Edit > Find > Find Action.

**Comment by BenDol** [comment]
Cant seem to reproduce this on my version.

**Comment by Mignari** [comment]
It seems to happen only for the default forgotten map.

**Comment by HeavenIsLost** [comment]
what is missing for this to be merged? the crash fix?

**Comment by Elime1** [comment]
@Mignari what is the status on this?

**Comment by Mignari** [comment]
The Search for Item window was completely rewritten in the latest version of the editor. It is now possible to search by server id, client id, name, type and item properties.
To search for actionid/uniqueid makes more sense to use the menu for this.
Edit > Find on Map > Find Unique
Edit > Find on Map > Find Action
Edit > Find on Selected Area > Find Unique
Edit > Find on Selected Area > Find Action

**Pull request closed without merging**
