### PR TITLE
.gitignore binary from compilation (rme)

### PR DESCRIPTION
**Pull request by slowaways**

### CODE REVIEW

**Comment by gpedro** [comment]
windows compilation produces binary in a root folder? because linux & OS X produces inside `build` folder

**Comment by slowaways** [comment]
Yes, but you can move the binary to the root folder while contributing code developing.
screenshot_20161122_121322
Let this commit not be just for my local repository.

**Comment by Elime1** [comment]
It does make som sense since rme will still find the data folder after moving it to the root folder. But one could argue that you should create a new folder somewhere else and copy/move the data folder and executable there instead.

**Comment by gpedro** [comment]
it's not necessary but maybe this can be useful any day

**Pull request merged**
