### PR TITLE
Update borders.xml

### PR DESCRIPTION
**Pull request by glombers**

### CODE REVIEW

**Comment by Elime1** [comment]
Hello! I haven't looked much at how this works but I get warnings on startup:
skarmavbild 2016-12-22 kl 15 49 53

**Comment by glombers** [comment]
@Elime1 map version ?

**Comment by Elime1** [comment]
10.98

**Comment by glombers** [comment]
you need put this file here https://github.com/hjnilsson/rme/tree/master/data/1098

**Comment by Elime1** [comment]
I cloned your repository. So I have all your changes.

**Comment by glombers** [comment]
these changes has not added by @hjnilsson  I hope that sorting useful to you. I am a lover of open tibia and this will make it easier to create ots for new versions!

**Comment by Elime1** [comment]
I'm not questioning your intentions, it's just that it doesn't work when I try it. I cloned your repository glombers/rme and it doesn't work for me. Maybe there is something wrong on my end? Did you try making a fresh clone of your repository, compile and see if it works?

**Comment by glombers** [comment]
see it works! http://i.imgur.com/fYHr8ec.gif

**Comment by Elime1** [comment]
Looks great. But all I get is:
warnings

**Comment by Elime1** [comment]
Looks like you forgot to commit tilesets.xml

**Pull request closed without merging**
