### PR TITLE
Building in Windows with libarchive and freeglut from vcpkg

### PR DESCRIPTION
**Pull request by gustavomb**
* Removing now unused 'dependencies' folder
* Organizing VS solution configuration files

### CODE REVIEW

**Comment by comedinha** [comment]
Freeglut is not crashing on windows?
https://github.com/hjnilsson/rme/blob/master/source/application.cpp#L118

He only initialize on linux.

**Comment by gustavomb** [comment]
I don't know if glInit is really necessary in Windows, but it's working both with and without it, at least when building with Visual Studio.
How are you setting up your MinGW environment? Were you building it with the included binaries in the dependencies folder?

**Comment by comedinha** [comment]
> I don't know if glInit is really necessary in Windows, but it's working both with and without it, at least when building with Visual Studio.
> How are you setting up your MinGW environment? Were you building it with the included binaries in the dependencies folder?

I setup my environment using vcpkg, when some tooltip appears on the screen the editor crash because glut is not initialized.
If the screen not contain tooltips the editor not crash.

**Comment by CristoferMartins** [comment]
I made the same change(drop dependencies folder and started using vcpkg libarchive and glut) and i can confirm the call to glutInit is needed in windows too(had the same issue as comedinha).

**Comment by gustavomb** [comment]
Sorry guys, for some reason I failed to test tooltips, the only feature that seems to make use of the glut library.
The problem is the FREEGLUT_EXIT_IF_NOT_INITIALISED check that is done the very first time some glut function is called, and it exits with code 1 when it's not initialized. I'll commit the fix later today.

**Comment by gustavomb** [comment]
It's now fixed and working as intended.

**Comment by Mignari** [comment]
Thanks!

**Comment by Erza** [comment]
I just adopted this change, and I noticed that this breaks the tooltip texts.
153324216G

On the left tooltip, you can observe an extra space being added before the `uid: 20009` 
On the right tooltip you can observe a random line break being added between `id: ` and `2012`, as well as the text of the sign being drawn outside of the tooltip.

The offending code is in this area here: https://github.com/hjnilsson/rme/blob/master/source/map_drawer.cpp#L1597-L1693
I'm not set up to be debugging the problem right now, would be great if anyone could pitch in on the issue.

**Pull request merged**
